version: '3'

services:
  flutter-env-service:
    build:
      context: .
    ports:
      - "8889:8889"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8889
    restart: unless-stopped
