name: jb_report_app
description: JB Report Platform Mobile Application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  
  # State Management (Riverpod only)
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  
  # Navigation
  go_router: ^13.2.4
  
  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  pretty_dio_logger: ^1.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  
  # Database
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # Image & Camera
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  image: ^4.1.7
  
  # Files
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  
  # Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_naver_map: ^1.2.2
  
  # URL & Browser
  url_launcher: ^6.2.4
  
  # Charts & Visualization
  fl_chart: ^0.68.0
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Notifications
  flutter_local_notifications: ^17.0.1
  
  # Firebase
  firebase_core: ^3.4.0
  firebase_crashlytics: ^4.1.0
  
  # Authentication
  local_auth: ^2.1.8
  google_sign_in: ^6.2.0
  
  # Utilities
  intl: ^0.20.2
  timeago: ^3.6.1
  share_plus: ^7.2.2
  connectivity_plus: ^5.0.2
  uuid: ^4.3.3
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  
  # PDF & Printing
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Device Info
  device_info_plus: ^10.1.0
  package_info_plus: ^7.0.0
  
  # Security
  crypto: ^3.0.3
  kakao_flutter_sdk_user: ^1.9.5
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  analyzer: ^6.4.1
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.3.11
  
  # Flavor
  flutter_flavorizr: ^2.2.1
  
  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter

# Flutter configuration
flutter:
  uses-material-design: true
  
  # Asset directories - these directories have been created with placeholder files
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

# Flavorizr configuration
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios: {}

  flavors:
    development:
      app:
        name: "JB Platform Dev"
      android:
        applicationId: "com.jeonbuk.report.dev"
      ios:
        bundleId: "com.jeonbuk.report.dev"

    staging:
      app:
        name: "JB Platform Staging"
      android:
        applicationId: "com.jeonbuk.report.staging"
      ios:
        bundleId: "com.jeonbuk.report.staging"

    production:
      app:
        name: "JB Platform"
      android:
        applicationId: "com.jeonbuk.report"
      ios:
        bundleId: "com.jeonbuk.report"
    
  # Fonts configuration
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
