global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://eureka-server:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__address__, __meta_eureka_app_instance_metadata_metrics_path]
        regex: ([^:]+)(?::\d+)?;(/.*)?
        replacement: $1:8080$2
        target_label: __address__
        action: replace
      - source_labels: [__meta_eureka_app_name]
        regex: 'API-GATEWAY'
        action: keep

  - job_name: 'main-api-server'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://eureka-server:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__meta_eureka_app_name]
        regex: 'MAIN-API-SERVER'
        action: keep

  - job_name: 'ai-analysis-server'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://eureka-server:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_app_instance_metadata_metrics_path]
        target_label: __metrics_path__
      - source_labels: [__meta_eureka_app_name]
        regex: 'AI-ANALYSIS-SERVER'
        action: keep
