name: flutter_report_app
description: 현장 보고 및 관리 통합 플랫폼
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # 상태 관리
  provider: ^6.1.5

  # 네트워킹
  dio: ^5.8.0+1
  connectivity_plus: ^5.0.2
  http: ^1.1.0

  # 로컬 저장소
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 인증
  google_sign_in: ^6.3.0
  kakao_flutter_sdk: ^1.9.7+3
  flutter_naver_login: ^1.8.0
  oauth2: ^2.0.3

  # 위치 및 지도
  geolocator: ^10.1.1
  geocoding: ^2.2.2
  google_maps_flutter: ^2.12.3

  # 카메라 및 이미지
  camera: ^0.10.6
  image_picker: ^1.1.2
  image: ^4.5.4

  # 서명
  signature: ^5.5.0

  # 파일 처리
  path_provider: ^2.1.5
  path: ^1.9.1

  # 푸시 알림 (모바일 전용)
  flutter_local_notifications: ^16.3.3

  # UI 컴포넌트
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0

  # 권한 관리
  permission_handler: ^11.4.0

  # 유틸리티
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  json_annotation: ^4.9.0

# Firebase 패키지 버전 호환성 강제 설정 (웹 호환성 문제로 제거)
# dependency_overrides:
#   firebase_core: 2.24.2
#   firebase_core_platform_interface: 4.8.0
#   firebase_core_web: 2.8.1
#   firebase_messaging: 14.7.4
#   firebase_messaging_platform_interface: 4.5.18
#   firebase_messaging_web: 3.5.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/  # 폰트 폴더 전체 추가
  
  # 웹 호환성을 위해 폰트는 선택적으로 사용
  # fonts:
  #   - family: NotoSansKR
  #     fonts:
  #       - asset: assets/fonts/NotoSansKR-Regular.ttf
  #       - asset: assets/fonts/NotoSansKR-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/NotoSansKR-Bold.ttf
  #         weight: 700
