name: jb_report_app
description: JB Report Platform Mobile Application
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  
  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.1.5
  
  # Navigation
  go_router: ^16.0.0
  
  # Network
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0
  cookie_jar: ^4.0.8
  
  # Local Storage
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^10.0.0-beta.4
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Image & Camera
  image_picker: ^1.0.4
  camera: ^0.11.2
  image: ^4.1.3
  
  # Files
  file_picker: ^10.2.0
  path_provider: ^2.1.1
  
  # Maps
  flutter_naver_map: ^1.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Charts & Visualization
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.39
  syncfusion_flutter_pdfviewer: ^30.1.39
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.2.9
  
  # Authentication
  local_auth: ^2.1.6
  
  # Utilities
  intl: ^0.20.2
  timeago: ^3.5.0
  url_launcher: ^6.1.14
  share_plus: ^11.0.0
  connectivity_plus: ^6.1.4
  
  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  
  # PDF & Printing
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Firebase
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  retrofit: ^4.6.0
  jwt_decoder: ^2.0.1
  google_sign_in: ^7.1.0
  kakao_flutter_sdk_user: ^1.9.7+3
  pretty_dio_logger: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  freezed: ^3.1.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  retrofit_generator: ^9.7.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
